---
title: "Target Trial Design Assistant Launch Page"
author: "Todd R. Johnson"
format: html
editor: visual
bibliography: references.bib
---

This is main launch page to the latest version of an AI-powered Claude tool that will help you design a study to estimate causal effects from observational data.

The tool uses the TARGET guidelines [@cashin2025] to walk you through the elements needed to design an ideal pragmatic clinical trial and then how to emulate that trial using observational data.

I developed this tool based on our review of tools for supporting target trial emulations, which showed that there were no tools to support the early, and most critical, stages of target trial emulation–clearly specifying the causal question and the study design [@vanhal2025]. Many tools support the identification and estimation phases, but without a well-defined causal question and study design, even the best analysis will produce poor results.

This page will always link to the latest version of the tool. Claude changes the URL for each version, so it is best to bookmark this page.

Once you click below, you will be asked to log in to Claude.ai. You must have a paid account to use the tool and your usage counts against your credit. However, in my opinion Claude is well worth the price and Claude Pro is sufficient for normal use.

Please provide feedback at the GitHub repo: <https://github.com/tjohnson250/TTDA>

or by emailing me at todd.r.johnson\@uth.tmc.edu

```{=html}
<iframe src="https://claude.site/public/artifacts/e6d45ee9-f72c-4863-8ae4-6672f0f41f5f/embed" title="Claude Artifact" width="100%" height="600" frameborder="0" allow="clipboard-write" allowfullscreen></iframe>
```
